# configuration for pre-commit git hooks
repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.277
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

# Local hooks (project-specific)
- repo: local
  hooks:
    - id: run-unittests
      name: Run unit tests (unittest discover)
      entry: python -m unittest discover -v
      language: system
      pass_filenames: false
      types: [python]
